sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t yeeyunjie/docker-react:1.0 .

script:
  - docker run -e CI=true yeeyunjie/docker-react:1.0 npm run test 